version: "3.7"
services:
  db:
    image: postgres
    env_file:
      - ./db/config.env
    volumes:
      - ./db/volumes:/var/lib/postgresql/data
  api:
    build: ./api
    restart: always
    env_file: ./api/.env
    ports:
      - 80
    environment:
      # db/config.env - Configuration
      TYPEORM_URL: postgres://postgres:postgres@db/postgres
    depends_on:
      - db
  web:
    build: ./proxy
    # volumes:
    #   - ./proxy/templates:/etc/nginx/templates
    ports:
      - 80:80
