version: "3.7"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./db/config.env
    volumes:
      - ./db/volumes:/var/lib/postgresql/data
  api:
    build: ./api
    ports:
      - 8080:8080
    restart: always
    env_file: ./api/.env
    environment:
      TYPEORM_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
