version: "3.7"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/volumes:/var/lib/postgresql/data
  api:
    build: ./api
    ports:
      - 8080:8080
    restart: always
    env_file: api/.env
    environment:
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      JWT_REFRESH_TOKEN_EXP: 1 week
      JWT_REFRESH_TOKEN: secret1
      JWT_ACCESS_TOKEN_EXP: 8 hour
      JWT_ACCESS_TOKEN: secret2
      HASH_SALT: 10
    depends_on:
      - postgres