openapi: 3.0.1
info:
  title: koa-jwt-auth
  description: API.
  version: 1.0.0
servers:
  - url: "/"
paths:
  /v1/user/{id}:
    get:
      summary: Find one user
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        200:
          description: Success
        404:
          description: User not found

    delete:
      summary: Delete user
      tags:
        - User
      parameters:
        - name: id
          required: true
          in: path
          description: User ID
          schema:
            type: string
      responses:
        200:
          description: Success
        404:
          description: User not found.

    patch:
      summary: Update user
      tags:
        - User
      parameters:
        - name: id
          required: true
          in: path
          description: User ID
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: updatedUser
                password:
                  type: string
                  example: updatedPassword
                email:
                  type: string
                  example: updatedEmail@email.com
      responses:
        200:
          description: Success
        404:
          description: User not found

  /v1/user:
    get:
      summary: Find all users
      tags:
        - User
      responses:
        200:
          description: Success
        404:
          description: No user found
    post:
      summary: Create user
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: createUser
                password:
                  type: string
                  example: createPassword
                email:
                  type: string
                  example: createEmail@email.com
      responses:
        201:
          description: Success

  /v1/login:
    post:
      summary: Authenticate user
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: myUsername
                password:
                  type: string
                  example: myPassword
                email:
                  type: string
                  example: myEmail@email.com
      responses:
        200:
          description: Success
        400:
          description: Invalid password
